name: package-goat-ui

on:
  push:
    branches:
      - main

jobs:
  build-and-push-goat:
    runs-on: ubuntu-latest
    steps:
      - id: genomehubs
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: genomehubs/genomehubs
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          git clone -b ${{ steps.genomehubs.outputs.release }} https://github.com/genomehubs/genomehubs
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: genomehubs/goat
      - name: Build and push GoaT image with content from repo
        uses: docker/build-push-action@v5
        with:
          context: .
          file: genomehubs/src/docker/ui/Dockerfile.site
          push: true
          build-args: |
            BASE_IMAGE=genomehubs/genomehubs-ui:${{ steps.genomehubs.outputs.release }}
            SITE_REPO=genomehubs/goat-ui
            SITE_BRANCH=main
            SITE_NAME=GoaT
            SITE_NAME_LONG=Genomes on a Tree
            GH_CITATION_URL=https://doi.org/10.12688/wellcomeopenres.18658.1
            GH_SUGGESTED_TERM=Canidae
            GH_TAXONOMY=ncbi
          tags: |
            genomehubs/goat:${{ steps.genomehubs.outputs.release }}
            genomehubs/goat:latest
          labels: ${{ steps.meta.outputs.labels }}
